assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS01SBPS-PC01A-4B-PHSENA102
stream:
  method: streamed
  name: phsen_thermistor_voltage
workflow_config:
  schedule: 0 0 * * *
